import React from 'react';
import HeroSection from '../components/common/HeroSection';
import FeatureCard from '../components/common/FeatureCard';
import CTAButtons from '../components/common/CTAButtons';

const Environment: React.FC = () => {
  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <HeroSection
        badge={{
          text: '🚀 Next-Generation Benchmark Platform',
          variant: 'default',
        }}
        title={['Interactive AI-Generated', 'Environments']}
        description="Experience dynamic GUI testing environments generated by AI, providing unique and fair evaluation scenarios for every agent test. Explore our comprehensive test cases that demonstrate the challenges agents face in these environments."
        buttons={[
          {
            text: 'Explore Environments',
            onClick: () => {},
            variant: 'primary-on-warm',
          },
          {
            text: 'View Documentation',
            onClick: () => {},
            variant: 'secondary-on-warm',
          },
        ]}
        backgroundVariant="warm-gradient"
        showPulseDots={true}
      />

      {/* Interactive Demo Section - Full Width with Visual Separation */}
      <div className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-6">
              <div className="inline-flex items-center space-x-2 bg-coral-100 text-coral-700 px-4 py-2 rounded-full text-sm font-medium">
                <div className="w-2 h-2 bg-coral-500 rounded-full animate-pulse"></div>
                Live Interactive Demo
              </div>
              <h2 className="text-3xl md:text-4xl font-bold text-gray-900 leading-tight">
                Experience Dynamic Environment Generation
              </h2>
              <p className="text-lg text-gray-600 leading-relaxed">
                Explore our AI-generated GUI environments where each evaluation
                creates a unique testing scenario, ensuring agents demonstrate
                genuine problem-solving capabilities rather than memorized
                solutions.
              </p>
              <div className="flex flex-col sm:flex-row gap-4">
                <div className="flex items-center space-x-3">
                  <div className="w-12 h-12 bg-warm-100 rounded-xl flex items-center justify-center">
                    <svg
                      className="w-6 h-6 text-warm-600"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                    >
                      <path
                        fillRule="evenodd"
                        d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                        clipRule="evenodd"
                      />
                    </svg>
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-900">
                      Unique Per Session
                    </h3>
                    <p className="text-sm text-gray-600">
                      No two evaluations are identical
                    </p>
                  </div>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-12 h-12 bg-coral-100 rounded-xl flex items-center justify-center">
                    <svg
                      className="w-6 h-6 text-coral-600"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                    >
                      <path
                        fillRule="evenodd"
                        d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                        clipRule="evenodd"
                      />
                    </svg>
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-900">
                      Real-time Testing
                    </h3>
                    <p className="text-sm text-gray-600">
                      Live agent interaction
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div className="relative">
              <div className="card shadow-2xl p-8 bg-gradient-to-br from-gray-50 to-white border border-gray-100">
                <div className="aspect-video bg-gradient-to-br from-warm-100 to-coral-100 rounded-xl flex items-center justify-center mb-6 relative overflow-hidden">
                  <div className="absolute inset-0 opacity-10">
                    <div className="grid grid-cols-8 grid-rows-6 h-full">
                      {Array.from({ length: 48 }).map((_, i) => (
                        <div key={i} className="border border-warm-300"></div>
                      ))}
                    </div>
                  </div>
                  <div className="relative z-10 text-center">
                    <div className="w-20 h-20 bg-white rounded-full flex items-center justify-center mx-auto mb-4 shadow-lg">
                      <svg
                        className="w-10 h-10 text-coral-600"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth="2"
                          d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"
                        />
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth="2"
                          d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                        />
                      </svg>
                    </div>
                    <p className="text-gray-700 font-medium">
                      Interactive Environment Preview
                    </p>
                  </div>
                </div>
                <div className="grid grid-cols-3 gap-4">
                  <div className="text-center">
                    <div className="text-2xl font-bold text-warm-600">527</div>
                    <div className="text-xs text-gray-600">Test Cases</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-coral-600">
                      100%
                    </div>
                    <div className="text-xs text-gray-600">Unique</div>
                  </div>
                  <div className="text-center">
                    <div className="text-2xl font-bold text-gold-600">3</div>
                    <div className="text-xs text-gray-600">Platforms</div>
                  </div>
                </div>
              </div>
              <div className="absolute -top-4 -right-4 w-24 h-24 bg-gradient-to-br from-coral-400 to-coral-600 rounded-full opacity-20 blur-xl"></div>
              <div className="absolute -bottom-4 -left-4 w-32 h-32 bg-gradient-to-br from-warm-400 to-warm-600 rounded-full opacity-20 blur-xl"></div>
            </div>
          </div>
        </div>
      </div>

      {/* Environment Features Section - Full Width with Varied Layout */}
      <div className="py-20 bg-gradient-to-br from-warm-50 to-coral-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="inline-flex items-center space-x-2 bg-warm-100 text-warm-700 px-4 py-2 rounded-full text-sm font-medium mb-6">
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
              </svg>
              Core Capabilities
            </div>
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
              Advanced Environment Features
            </h2>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              Our AI-powered environment generation system provides
              comprehensive testing capabilities that ensure fair evaluation and
              prevent agent memorization.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Featured Feature - Larger */}
            <div className="lg:col-span-2">
              <FeatureCard
                variant="featured"
                title="Dynamic GUI Generation"
                description="Our advanced AI creates completely unique interfaces, layouts, and interaction patterns for each evaluation session. Every test generates fresh environments that prevent memorization and ensure genuine problem-solving assessment."
                tags={['Unique Per Session', 'Adaptive Layouts', 'AI-Powered']}
                colorTheme="warm"
                borderAccent={true}
                icon={
                  <svg
                    className="w-8 h-8 text-white"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M13 10V3L4 14h7v7l9-11h-7z"
                    />
                  </svg>
                }
              />
            </div>

            {/* Secondary Features */}
            <FeatureCard
              title="Real-time Interaction"
              description="Live testing scenarios where agents can click, type, navigate, and manipulate interface elements with immediate feedback."
              colorTheme="coral"
              icon={
                <svg
                  className="w-6 h-6 text-white"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M15 15l-2 5L9 9l11 4-5 2z"
                  />
                </svg>
              }
            />

            <FeatureCard
              title="Variable Complexity"
              description="Environments adapt in complexity based on agent capabilities and evaluation requirements for fair assessment."
              colorTheme="gold"
              icon={
                <svg
                  className="w-6 h-6 text-white"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"
                  />
                </svg>
              }
            />

            <FeatureCard
              title="Multi-step Tasks"
              description="Complex scenarios requiring agents to complete sequences of actions to achieve goals with state preservation."
              colorTheme="warm"
              icon={
                <svg
                  className="w-6 h-6 text-white"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01"
                  />
                </svg>
              }
            />

            <FeatureCard
              title="State Management"
              description="Comprehensive state tracking and persistence for complex multi-step workflows with memory preservation."
              colorTheme="coral"
              icon={
                <svg
                  className="w-6 h-6 text-white"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"
                  />
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                  />
                </svg>
              }
            />
          </div>
        </div>
      </div>

      {/* Environment Categories Section - Enhanced Visual Hierarchy */}
      <div className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="inline-flex items-center space-x-2 bg-coral-100 text-coral-700 px-4 py-2 rounded-full text-sm font-medium mb-6">
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path
                  fillRule="evenodd"
                  d="M12.395 2.553a1 1 0 00-1.45-.385c-.345.23-.614.558-.822.88-.214.33-.403.713-.57 1.116-.334.804-.614 1.768-.84 2.734a31.365 31.365 0 00-.613 3.58 2.64 2.64 0 01-.945-1.067c-.328-.68-.398-1.534-.398-2.654A1 1 0 005.05 6.05 6.981 6.981 0 003 11a7 7 0 1011.95-4.95c-.592-.591-.98-.985-1.348-1.467-.363-.476-.724-1.063-1.207-2.03zM12.12 15.12A3 3 0 017 13s.879.5 2.5.5c0-1 .5-4 1.25-4.5.5 1 .786 1.293 1.371 1.879A2.99 2.99 0 0113 13a2.99 2.99 0 01-.879 2.121z"
                  clipRule="evenodd"
                />
              </svg>
              Platform Coverage
            </div>
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
              Multi-Platform Environment Support
            </h2>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              Our benchmark platform supports comprehensive testing across web,
              desktop, and mobile interfaces, ensuring agents can perform
              effectively in diverse environments.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Web Applications - Featured */}
            <div className="benchmark-card group relative">
              <div className="benchmark-card-glow absolute -inset-1 bg-gradient-to-r from-warm-400 to-warm-600 rounded-2xl opacity-0 group-hover:opacity-25 transition-all duration-500 ease-out blur-xl"></div>
              <div className="relative card p-8 bg-white border-2 border-warm-100 shadow-xl group-hover:shadow-2xl group-hover:-translate-y-1 transition-all duration-300 ease-out">
                <div className="text-center">
                  <div className="w-20 h-20 bg-gradient-to-br from-warm-400 to-warm-600 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg group-hover:scale-110 transition-transform duration-300 ease-out">
                    <svg
                      className="w-10 h-10 text-white"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9"
                      />
                    </svg>
                  </div>
                  <h3 className="text-2xl font-bold text-gray-900 mb-4 group-hover:scale-105 transition-transform duration-300">
                    Web Applications
                  </h3>
                  <p className="text-gray-600 leading-relaxed mb-6 group-hover:text-warm-600 transition-colors duration-300">
                    Dynamic web interfaces with complex forms, navigation
                    systems, and interactive components that mirror real-world
                    web applications.
                  </p>
                  <div className="space-y-3 text-left">
                    <div className="flex items-center space-x-3 group-hover:text-warm-600 transition-colors duration-300">
                      <div className="w-5 h-5 bg-warm-100 rounded-full flex items-center justify-center flex-shrink-0 group-hover:bg-warm-200 transition-colors duration-300">
                        <svg
                          className="w-3 h-3 text-warm-600 group-hover:text-warm-700 transition-colors duration-300"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path
                            fillRule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clipRule="evenodd"
                          />
                        </svg>
                      </div>
                      <span className="text-sm text-gray-700">
                        React/Vue/Angular apps
                      </span>
                    </div>
                    <div className="flex items-center space-x-3 group-hover:text-warm-600 transition-colors duration-300">
                      <div className="w-5 h-5 bg-warm-100 rounded-full flex items-center justify-center flex-shrink-0 group-hover:bg-warm-200 transition-colors duration-300">
                        <svg
                          className="w-3 h-3 text-warm-600 group-hover:text-warm-700 transition-colors duration-300"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path
                            fillRule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clipRule="evenodd"
                          />
                        </svg>
                      </div>
                      <span className="text-sm text-gray-700">
                        Form validation & handling
                      </span>
                    </div>
                    <div className="flex items-center space-x-3 group-hover:text-warm-600 transition-colors duration-300">
                      <div className="w-5 h-5 bg-warm-100 rounded-full flex items-center justify-center flex-shrink-0 group-hover:bg-warm-200 transition-colors duration-300">
                        <svg
                          className="w-3 h-3 text-warm-600 group-hover:text-warm-700 transition-colors duration-300"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path
                            fillRule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clipRule="evenodd"
                          />
                        </svg>
                      </div>
                      <span className="text-sm text-gray-700">
                        Responsive design testing
                      </span>
                    </div>
                  </div>
                  <div className="mt-6 pt-6 border-t border-warm-100">
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-medium text-warm-600 group-hover:text-warm-700 transition-colors duration-300">
                        312 Test Cases
                      </span>
                      <span className="text-xs bg-warm-100 text-warm-700 px-2 py-1 rounded-full font-medium group-hover:bg-warm-200 transition-colors duration-300">
                        59%
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Desktop Apps */}
            <div className="benchmark-card group relative">
              <div className="benchmark-card-glow absolute -inset-1 bg-gradient-to-r from-coral-400 to-coral-600 rounded-2xl opacity-0 group-hover:opacity-25 transition-all duration-500 ease-out blur-xl"></div>
              <div className="relative card p-8 bg-white border-2 border-coral-100 shadow-xl group-hover:shadow-2xl group-hover:-translate-y-1 transition-all duration-300 ease-out">
                <div className="text-center">
                  <div className="w-20 h-20 bg-gradient-to-br from-coral-400 to-coral-600 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg group-hover:scale-110 transition-transform duration-300 ease-out">
                    <svg
                      className="w-10 h-10 text-white"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z"
                      />
                    </svg>
                  </div>
                  <h3 className="text-2xl font-bold text-gray-900 mb-4 group-hover:scale-105 transition-transform duration-300">
                    Desktop Apps
                  </h3>
                  <p className="text-gray-600 leading-relaxed mb-6 group-hover:text-coral-600 transition-colors duration-300">
                    Native application interfaces with complex workflows, state
                    management, and desktop-specific interaction patterns.
                  </p>
                  <div className="space-y-3 text-left">
                    <div className="flex items-center space-x-3 group-hover:text-coral-600 transition-colors duration-300">
                      <div className="w-5 h-5 bg-coral-100 rounded-full flex items-center justify-center flex-shrink-0 group-hover:bg-coral-200 transition-colors duration-300">
                        <svg
                          className="w-3 h-3 text-coral-600 group-hover:text-coral-700 transition-colors duration-300"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path
                            fillRule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clipRule="evenodd"
                          />
                        </svg>
                      </div>
                      <span className="text-sm text-gray-700">
                        Electron/Qt/WPF apps
                      </span>
                    </div>
                    <div className="flex items-center space-x-3 group-hover:text-coral-600 transition-colors duration-300">
                      <div className="w-5 h-5 bg-coral-100 rounded-full flex items-center justify-center flex-shrink-0 group-hover:bg-coral-200 transition-colors duration-300">
                        <svg
                          className="w-3 h-3 text-coral-600 group-hover:text-coral-700 transition-colors duration-300"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path
                            fillRule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clipRule="evenodd"
                          />
                        </svg>
                      </div>
                      <span className="text-sm text-gray-700">
                        Menu & navigation systems
                      </span>
                    </div>
                    <div className="flex items-center space-x-3 group-hover:text-coral-600 transition-colors duration-300">
                      <div className="w-5 h-5 bg-coral-100 rounded-full flex items-center justify-center flex-shrink-0 group-hover:bg-coral-200 transition-colors duration-300">
                        <svg
                          className="w-3 h-3 text-coral-600 group-hover:text-coral-700 transition-colors duration-300"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path
                            fillRule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clipRule="evenodd"
                          />
                        </svg>
                      </div>
                      <span className="text-sm text-gray-700">
                        File system operations
                      </span>
                    </div>
                  </div>
                  <div className="mt-6 pt-6 border-t border-coral-100">
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-medium text-coral-600 group-hover:text-coral-700 transition-colors duration-300">
                        134 Test Cases
                      </span>
                      <span className="text-xs bg-coral-100 text-coral-700 px-2 py-1 rounded-full font-medium group-hover:bg-coral-200 transition-colors duration-300">
                        25%
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Mobile Interfaces */}
            <div className="benchmark-card group relative">
              <div className="benchmark-card-glow absolute -inset-1 bg-gradient-to-r from-gold-400 to-gold-600 rounded-2xl opacity-0 group-hover:opacity-25 transition-all duration-500 ease-out blur-xl"></div>
              <div className="relative card p-8 bg-white border-2 border-gold-100 shadow-xl group-hover:shadow-2xl group-hover:-translate-y-1 transition-all duration-300 ease-out">
                <div className="text-center">
                  <div className="w-20 h-20 bg-gradient-to-br from-gold-400 to-gold-600 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg group-hover:scale-110 transition-transform duration-300 ease-out">
                    <svg
                      className="w-10 h-10 text-white"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z"
                      />
                    </svg>
                  </div>
                  <h3 className="text-2xl font-bold text-gray-900 mb-4 group-hover:scale-105 transition-transform duration-300">
                    Mobile Interfaces
                  </h3>
                  <p className="text-gray-600 leading-relaxed mb-6 group-hover:text-gold-600 transition-colors duration-300">
                    Touch-optimized interfaces with gestures, responsive
                    layouts, and mobile-specific interaction patterns.
                  </p>
                  <div className="space-y-3 text-left">
                    <div className="flex items-center space-x-3 group-hover:text-gold-600 transition-colors duration-300">
                      <div className="w-5 h-5 bg-gold-100 rounded-full flex items-center justify-center flex-shrink-0 group-hover:bg-gold-200 transition-colors duration-300">
                        <svg
                          className="w-3 h-3 text-gold-600 group-hover:text-gold-700 transition-colors duration-300"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path
                            fillRule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clipRule="evenodd"
                          />
                        </svg>
                      </div>
                      <span className="text-sm text-gray-700">
                        iOS/Android apps
                      </span>
                    </div>
                    <div className="flex items-center space-x-3 group-hover:text-gold-600 transition-colors duration-300">
                      <div className="w-5 h-5 bg-gold-100 rounded-full flex items-center justify-center flex-shrink-0 group-hover:bg-gold-200 transition-colors duration-300">
                        <svg
                          className="w-3 h-3 text-gold-600 group-hover:text-gold-700 transition-colors duration-300"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path
                            fillRule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clipRule="evenodd"
                          />
                        </svg>
                      </div>
                      <span className="text-sm text-gray-700">
                        Gesture recognition
                      </span>
                    </div>
                    <div className="flex items-center space-x-3 group-hover:text-gold-600 transition-colors duration-300">
                      <div className="w-5 h-5 bg-gold-100 rounded-full flex items-center justify-center flex-shrink-0 group-hover:bg-gold-200 transition-colors duration-300">
                        <svg
                          className="w-3 h-3 text-gold-600 group-hover:text-gold-700 transition-colors duration-300"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path
                            fillRule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clipRule="evenodd"
                          />
                        </svg>
                      </div>
                      <span className="text-sm text-gray-700">
                        Responsive testing
                      </span>
                    </div>
                  </div>
                  <div className="mt-6 pt-6 border-t border-gold-100">
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-medium text-gold-600 group-hover:text-gold-700 transition-colors duration-300">
                        81 Test Cases
                      </span>
                      <span className="text-xs bg-gold-100 text-gold-700 px-2 py-1 rounded-full font-medium group-hover:bg-gold-200 transition-colors duration-300">
                        16%
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Summary Stats */}
          <div className="mt-12 text-center">
            <div className="inline-flex items-center space-x-8 p-6 bg-gradient-to-r from-warm-50 to-coral-50 rounded-2xl">
              <div className="flex items-center space-x-3">
                <div className="w-10 h-10 bg-warm-500 rounded-full flex items-center justify-center">
                  <svg
                    className="w-5 h-5 text-white"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                </div>
                <div className="text-left">
                  <div className="text-2xl font-bold text-gray-900">527</div>
                  <div className="text-sm text-gray-600">Total Test Cases</div>
                </div>
              </div>
              <div className="text-gray-300">|</div>
              <div className="flex items-center space-x-3">
                <div className="w-10 h-10 bg-coral-500 rounded-full flex items-center justify-center">
                  <svg
                    className="w-5 h-5 text-white"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path d="M2 10a8 8 0 018-8v8h8a8 8 0 11-16 0z" />
                    <path d="M12 2.252A8.014 8.014 0 0117.748 8H12V2.252z" />
                  </svg>
                </div>
                <div className="text-left">
                  <div className="text-2xl font-bold text-gray-900">100%</div>
                  <div className="text-sm text-gray-600">AI Generated</div>
                </div>
              </div>
              <div className="text-gray-300">|</div>
              <div className="flex items-center space-x-3">
                <div className="w-10 h-10 bg-gold-500 rounded-full flex items-center justify-center">
                  <svg
                    className="w-5 h-5 text-white"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path d="M9 4.804A7.968 7.968 0 005.5 4c-1.255 0-2.443.29-3.5.804v10A7.969 7.969 0 015.5 14c1.669 0 3.218.51 4.5 1.385A7.962 7.962 0 0114.5 14c1.255 0 2.443.29 3.5.804v-10A7.968 7.968 0 0014.5 4c-1.255 0-2.443.29-3.5.804V12a1 1 0 11-2 0V4.804z" />
                  </svg>
                </div>
                <div className="text-left">
                  <div className="text-2xl font-bold text-gray-900">3</div>
                  <div className="text-sm text-gray-600">Platform Types</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Sample Test Cases Section - Enhanced Information Architecture */}
      <div className="py-20 bg-gradient-to-br from-coral-50 via-warm-50 to-gold-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="inline-flex items-center space-x-2 bg-gold-100 text-gold-700 px-4 py-2 rounded-full text-sm font-medium mb-6">
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path
                  fillRule="evenodd"
                  d="M3 3a1 1 0 000 2v8a2 2 0 002 2h2.586l-1.293 1.293a1 1 0 101.414 1.414L10 15.414l2.293 2.293a1 1 0 001.414-1.414L12.414 15H15a2 2 0 002-2V5a1 1 0 100-2H3zm11.707 4.293a1 1 0 00-1.414 0L10 10.586 8.707 9.293a1 1 0 00-1.414 0l-2 2a1 1 0 101.414 1.414L8 11.414l1.293 1.293a1 1 0 001.414 0l4-4a1 1 0 000-1.414z"
                  clipRule="evenodd"
                />
              </svg>
              Real-world Challenges
            </div>
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
              Sample Test Case Scenarios
            </h2>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              Explore the types of challenges agents face in our AI-generated
              environments. Each test case is designed to evaluate specific
              capabilities while ensuring fair assessment through dynamic
              generation.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-12">
            {/* Featured Test Case */}
            <div className="lg:col-span-3">
              <div className="benchmark-card group relative">
                <div className="benchmark-card-glow absolute -inset-1 bg-gradient-to-r from-warm-400 via-coral-400 to-gold-400 rounded-3xl opacity-20 group-hover:opacity-40 transition-all duration-500 ease-out blur-xl"></div>
                <div className="relative card p-8 bg-white shadow-xl border-0 overflow-hidden group-hover:shadow-2xl group-hover:-translate-y-1 transition-all duration-300 ease-out">
                  <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-warm-100 to-coral-100 rounded-full -mr-16 -mt-16 opacity-50"></div>
                  <div className="relative z-10">
                    <div className="flex items-start justify-between mb-6">
                      <div className="flex items-center space-x-3">
                        <div className="w-12 h-12 bg-gradient-to-br from-warm-400 to-warm-600 rounded-xl flex items-center justify-center shadow-lg group-hover:scale-110 transition-transform duration-300 ease-out">
                          <svg
                            className="w-6 h-6 text-white"
                            fill="none"
                            stroke="currentColor"
                            viewBox="0 0 24 24"
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeWidth="2"
                              d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                            />
                          </svg>
                        </div>
                        <div>
                          <span className="inline-block px-3 py-1 bg-warm-100 text-warm-700 rounded-full text-xs font-medium mb-2 group-hover:bg-warm-200 transition-colors duration-300">
                            Web Form
                          </span>
                          <h3 className="text-2xl font-bold text-gray-900 group-hover:scale-105 transition-transform duration-300">
                            Multi-Step Form Automation
                          </h3>
                        </div>
                      </div>
                      <span className="inline-flex items-center px-3 py-1 bg-red-100 text-red-700 rounded-full text-xs font-medium group-hover:bg-red-200 transition-colors duration-300">
                        <svg
                          className="w-3 h-3 mr-1 group-hover:text-red-800 transition-colors duration-300"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path
                            fillRule="evenodd"
                            d="M12.395 2.553a1 1 0 00-1.45-.385c-.345.23-.614.558-.822.88-.214.33-.403.713-.57 1.116-.334.804-.614 1.768-.84 2.734a31.365 31.365 0 00-.613 3.58 2.64 2.64 0 01-.945-1.067c-.328-.68-.398-1.534-.398-2.654A1 1 0 005.05 6.05 6.981 6.981 0 003 11a7 7 0 1011.95-4.95c-.592-.591-.98-.985-1.348-1.467-.363-.476-.724-1.063-1.207-2.03zM12.12 15.12A3 3 0 017 13s.879.5 2.5.5c0-1 .5-4 1.25-4.5.5 1 .786 1.293 1.371 1.879A2.99 2.99 0 0113 13a2.99 2.99 0 01-.879 2.121z"
                            clipRule="evenodd"
                          />
                        </svg>
                        Expert Level
                      </span>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                      <div>
                        <p className="text-gray-600 leading-relaxed mb-6 group-hover:text-gray-700 transition-colors duration-300">
                          Complex multi-step form validation with dynamic field
                          generation, conditional logic, and real-time error
                          handling. Tests agent&apos;s ability to handle
                          adaptive UI elements and maintain context across form
                          sections.
                        </p>

                        <div className="space-y-3">
                          <h4 className="font-semibold text-gray-900 mb-3 group-hover:text-gray-800 transition-colors duration-300">
                            Key Challenges:
                          </h4>
                          <div className="space-y-2">
                            <div className="flex items-start space-x-3 group-hover:text-warm-600 transition-colors duration-300">
                              <div className="w-5 h-5 bg-warm-100 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 group-hover:bg-warm-200 transition-colors duration-300">
                                <svg
                                  className="w-3 h-3 text-warm-600 group-hover:text-warm-700 transition-colors duration-300"
                                  fill="currentColor"
                                  viewBox="0 0 20 20"
                                >
                                  <path
                                    fillRule="evenodd"
                                    d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                                    clipRule="evenodd"
                                  />
                                </svg>
                              </div>
                              <div>
                                <span className="text-sm font-medium text-gray-900">
                                  Dynamic field validation
                                </span>
                                <p className="text-xs text-gray-600">
                                  Real-time form validation with conditional
                                  requirements
                                </p>
                              </div>
                            </div>
                            <div className="flex items-start space-x-3 group-hover:text-coral-600 transition-colors duration-300">
                              <div className="w-5 h-5 bg-coral-100 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 group-hover:bg-coral-200 transition-colors duration-300">
                                <svg
                                  className="w-3 h-3 text-coral-600 group-hover:text-coral-700 transition-colors duration-300"
                                  fill="currentColor"
                                  viewBox="0 0 20 20"
                                >
                                  <path
                                    fillRule="evenodd"
                                    d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                                    clipRule="evenodd"
                                  />
                                </svg>
                              </div>
                              <div>
                                <span className="text-sm font-medium text-gray-900">
                                  Multi-step navigation
                                </span>
                                <p className="text-xs text-gray-600">
                                  Context preservation across form sections
                                </p>
                              </div>
                            </div>
                            <div className="flex items-start space-x-3 group-hover:text-gold-600 transition-colors duration-300">
                              <div className="w-5 h-5 bg-gold-100 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 group-hover:bg-gold-200 transition-colors duration-300">
                                <svg
                                  className="w-3 h-3 text-gold-600 group-hover:text-gold-700 transition-colors duration-300"
                                  fill="currentColor"
                                  viewBox="0 0 20 20"
                                >
                                  <path
                                    fillRule="evenodd"
                                    d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                                    clipRule="evenodd"
                                  />
                                </svg>
                              </div>
                              <div>
                                <span className="text-sm font-medium text-gray-900">
                                  Error recovery
                                </span>
                                <p className="text-xs text-gray-600">
                                  Handling validation errors and retry scenarios
                                </p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>

                      <div className="space-y-4">
                        <div className="bg-gradient-to-br from-warm-50 to-coral-50 rounded-xl p-6 border border-warm-100 group-hover:from-warm-100 group-hover:to-coral-100 transition-all duration-300">
                          <h4 className="font-semibold text-gray-900 mb-4 group-hover:text-gray-800 transition-colors duration-300">
                            Success Metrics
                          </h4>
                          <div className="grid grid-cols-2 gap-4">
                            <div>
                              <div className="text-2xl font-bold text-warm-600 group-hover:scale-105 transition-transform duration-300">
                                95%
                              </div>
                              <div className="text-xs text-gray-600 group-hover:text-gray-700 transition-colors duration-300">
                                Form Completion
                              </div>
                            </div>
                            <div>
                              <div className="text-2xl font-bold text-coral-600 group-hover:scale-105 transition-transform duration-300">
                                87%
                              </div>
                              <div className="text-xs text-gray-600 group-hover:text-gray-700 transition-colors duration-300">
                                Error Handling
                              </div>
                            </div>
                          </div>
                        </div>

                        <div className="bg-gradient-to-br from-coral-50 to-gold-50 rounded-xl p-6 border border-coral-100 group-hover:from-coral-100 group-hover:to-gold-100 transition-all duration-300">
                          <h4 className="font-semibold text-gray-900 mb-3 group-hover:text-gray-800 transition-colors duration-300">
                            Test Variations
                          </h4>
                          <div className="flex flex-wrap gap-2">
                            <span className="px-2 py-1 bg-white rounded text-xs text-gray-700 group-hover:bg-gray-50 group-hover:text-gray-800 transition-colors duration-300">
                              3-10 fields
                            </span>
                            <span className="px-2 py-1 bg-white rounded text-xs text-gray-700 group-hover:bg-gray-50 group-hover:text-gray-800 transition-colors duration-300">
                              2-5 steps
                            </span>
                            <span className="px-2 py-1 bg-white rounded text-xs text-gray-700 group-hover:bg-gray-50 group-hover:text-gray-800 transition-colors duration-300">
                              15+ validation rules
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Standard Test Cases */}
            <div className="card p-6 bg-white shadow-lg hover:shadow-xl transition-all duration-300 group">
              <div className="flex items-center justify-between mb-4">
                <span className="inline-flex items-center px-3 py-1 bg-coral-100 text-coral-700 rounded-full text-xs font-medium">
                  <svg
                    className="w-3 h-3 mr-1"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M12.395 2.553a1 1 0 00-1.45-.385c-.345.23-.614.558-.822.88-.214.33-.403.713-.57 1.116-.334.804-.614 1.768-.84 2.734a31.365 31.365 0 00-.613 3.58 2.64 2.64 0 01-.945-1.067c-.328-.68-.398-1.534-.398-2.654A1 1 0 005.05 6.05 6.981 6.981 0 003 11a7 7 0 1011.95-4.95c-.592-.591-.98-.985-1.348-1.467-.363-.476-.724-1.063-1.207-2.03zM12.12 15.12A3 3 0 017 13s.879.5 2.5.5c0-1 .5-4 1.25-4.5.5 1 .786 1.293 1.371 1.879A2.99 2.99 0 0113 13a2.99 2.99 0 01-.879 2.121z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Advanced
                </span>
                <div className="w-10 h-10 bg-gradient-to-br from-coral-400 to-coral-600 rounded-lg flex items-center justify-center group-hover:scale-110 transition-transform">
                  <svg
                    className="w-5 h-5 text-white"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"
                    />
                  </svg>
                </div>
              </div>
              <h3 className="text-lg font-bold text-gray-900 mb-3">
                Complex Data Navigation
              </h3>
              <p className="text-sm text-gray-600 mb-4">
                Navigate complex data tables with sorting, filtering, and
                pagination while maintaining context and performing multi-step
                data operations.
              </p>
              <div className="space-y-2">
                <div className="flex items-center text-xs text-gray-600">
                  <svg
                    className="w-3 h-3 mr-2 text-coral-500"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Table sorting & filtering
                </div>
                <div className="flex items-center text-xs text-gray-600">
                  <svg
                    className="w-3 h-3 mr-2 text-coral-500"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Multi-row selection
                </div>
                <div className="flex items-center text-xs text-gray-600">
                  <svg
                    className="w-3 h-3 mr-2 text-coral-500"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Bulk operations
                </div>
              </div>
              <div className="mt-4 pt-4 border-t border-gray-100">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-medium text-coral-600">
                    124 variants
                  </span>
                  <div className="flex space-x-1">
                    <span className="w-2 h-2 bg-coral-500 rounded-full"></span>
                    <span className="w-2 h-2 bg-warm-500 rounded-full"></span>
                    <span className="w-2 h-2 bg-gold-500 rounded-full"></span>
                  </div>
                </div>
              </div>
            </div>

            <div className="card p-6 bg-white shadow-lg hover:shadow-xl transition-all duration-300 group">
              <div className="flex items-center justify-between mb-4">
                <span className="inline-flex items-center px-3 py-1 bg-gold-100 text-gold-700 rounded-full text-xs font-medium">
                  <svg
                    className="w-3 h-3 mr-1"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                  </svg>
                  Expert
                </span>
                <div className="w-10 h-10 bg-gradient-to-br from-gold-400 to-gold-600 rounded-lg flex items-center justify-center group-hover:scale-110 transition-transform">
                  <svg
                    className="w-5 h-5 text-white"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
                    />
                  </svg>
                </div>
              </div>
              <h3 className="text-lg font-bold text-gray-900 mb-3">
                Data Visualization Interaction
              </h3>
              <p className="text-sm text-gray-600 mb-4">
                Interactive charts and graphs requiring agents to interpret
                visual data, filter datasets, and extract insights from complex
                visualizations.
              </p>
              <div className="space-y-2">
                <div className="flex items-center text-xs text-gray-600">
                  <svg
                    className="w-3 h-3 mr-2 text-gold-500"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Chart interaction
                </div>
                <div className="flex items-center text-xs text-gray-600">
                  <svg
                    className="w-3 h-3 mr-2 text-gold-500"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Data filtering
                </div>
                <div className="flex items-center text-xs text-gray-600">
                  <svg
                    className="w-3 h-3 mr-2 text-gold-500"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Pattern recognition
                </div>
              </div>
              <div className="mt-4 pt-4 border-t border-gray-100">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-medium text-gold-600">
                    89 variants
                  </span>
                  <div className="flex space-x-1">
                    <span className="w-2 h-2 bg-gold-500 rounded-full"></span>
                    <span className="w-2 h-2 bg-coral-500 rounded-full"></span>
                    <span className="w-2 h-2 bg-warm-500 rounded-full"></span>
                  </div>
                </div>
              </div>
            </div>

            <div className="card p-6 bg-white shadow-lg hover:shadow-xl transition-all duration-300 group">
              <div className="flex items-center justify-between mb-4">
                <span className="inline-flex items-center px-3 py-1 bg-warm-100 text-warm-700 rounded-full text-xs font-medium">
                  <svg
                    className="w-3 h-3 mr-1"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path d="M9 2a1 1 0 000 2h2a1 1 0 100-2H9z" />
                    <path
                      fillRule="evenodd"
                      d="M4 5a2 2 0 012-2 1 1 0 000 2H6a2 2 0 100 4h2a2 2 0 100 4H6a2 2 0 100 4h2a1 1 0 100 2 2 2 0 01-2 2H4a2 2 0 01-2-2V5z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Intermediate
                </span>
                <div className="w-10 h-10 bg-gradient-to-br from-warm-400 to-warm-600 rounded-lg flex items-center justify-center group-hover:scale-110 transition-transform">
                  <svg
                    className="w-5 h-5 text-white"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
                    />
                  </svg>
                </div>
              </div>
              <h3 className="text-lg font-bold text-gray-900 mb-3">
                Authentication Workflows
              </h3>
              <p className="text-sm text-gray-600 mb-4">
                Multi-step login processes including MFA, social login, and
                secure session management with proper error handling.
              </p>
              <div className="space-y-2">
                <div className="flex items-center text-xs text-gray-600">
                  <svg
                    className="w-3 h-3 mr-2 text-warm-500"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Multi-factor auth
                </div>
                <div className="flex items-center text-xs text-gray-600">
                  <svg
                    className="w-3 h-3 mr-2 text-warm-500"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Social integration
                </div>
                <div className="flex items-center text-xs text-gray-600">
                  <svg
                    className="w-3 h-3 mr-2 text-warm-500"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Session management
                </div>
              </div>
              <div className="mt-4 pt-4 border-t border-gray-100">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-medium text-warm-600">
                    76 variants
                  </span>
                  <div className="flex space-x-1">
                    <span className="w-2 h-2 bg-warm-500 rounded-full"></span>
                    <span className="w-2 h-2 bg-coral-500 rounded-full"></span>
                    <span className="w-2 h-2 bg-gold-500 rounded-full"></span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Overall Statistics */}
          <div className="text-center">
            <div className="inline-block p-8 bg-white rounded-2xl shadow-lg">
              <h3 className="text-2xl font-bold text-gray-900 mb-6">
                Comprehensive Test Coverage
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-6">
                <div>
                  <div className="text-3xl font-bold text-gradient mb-2">
                    527
                  </div>
                  <div className="text-sm text-gray-600">Total Test Cases</div>
                </div>
                <div>
                  <div className="text-3xl font-bold text-warm-600 mb-2">
                    312
                  </div>
                  <div className="text-sm text-gray-600">Web Applications</div>
                </div>
                <div>
                  <div className="text-3xl font-bold text-coral-600 mb-2">
                    134
                  </div>
                  <div className="text-sm text-gray-600">Desktop Apps</div>
                </div>
                <div>
                  <div className="text-3xl font-bold text-gold-600 mb-2">
                    81
                  </div>
                  <div className="text-sm text-gray-600">Mobile Interfaces</div>
                </div>
              </div>
              <div className="pt-6 border-t border-gray-200">
                <p className="text-sm text-gray-600">
                  <span className="font-semibold text-gray-900">
                    100% AI-Generated
                  </span>{' '}
                  •
                  <span className="font-semibold text-gray-900">
                    {' '}
                    Never Repeated
                  </span>{' '}
                  •
                  <span className="font-semibold text-gray-900">
                    {' '}
                    Fair Evaluation
                  </span>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Technology Stack Section - Enhanced Visual Presentation */}
      <div className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="inline-flex items-center space-x-2 bg-warm-100 text-warm-700 px-4 py-2 rounded-full text-sm font-medium mb-6">
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path
                  fillRule="evenodd"
                  d="M12.316 3.051a1 1 0 01.633 1.265l-4 12a1 1 0 11-1.898-.632l4-12a1 1 0 011.265-.633zM5.707 6.293a1 1 0 010 1.414L3.414 10l2.293 2.293a1 1 0 11-1.414 1.414l-3-3a1 1 0 010-1.414l3-3a1 1 0 011.414 0zm8.586 0a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 11-1.414-1.414L16.586 10l-2.293-2.293a1 1 0 010-1.414z"
                  clipRule="evenodd"
                />
              </svg>
              Advanced Technology
            </div>
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-6">
              Generation Technology Stack
            </h2>
            <p className="text-lg text-gray-600 max-w-3xl mx-auto">
              Our cutting-edge technology stack powers the AI-driven environment
              generation system, ensuring unique, scalable, and reliable test
              scenarios for comprehensive agent evaluation.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {/* AI Generation Core */}
            <div className="card p-8 bg-gradient-to-br from-warm-50 to-white border-l-4 border-warm-500 shadow-lg hover:shadow-xl transition-all duration-300">
              <div className="w-16 h-16 bg-gradient-to-br from-warm-400 to-warm-600 rounded-2xl flex items-center justify-center mb-6 shadow-lg">
                <svg
                  className="w-8 h-8 text-white"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
                  />
                </svg>
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-4">
                AI-Powered Generation
              </h3>
              <p className="text-gray-600 leading-relaxed mb-6">
                Advanced machine learning models create unique GUI environments
                with varying complexity, layouts, and interaction patterns
                tailored for comprehensive agent testing.
              </p>
              <div className="space-y-3">
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-warm-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">
                    Neural network architecture
                  </span>
                </div>
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-warm-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Pattern recognition</span>
                </div>
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-warm-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Adaptive complexity</span>
                </div>
              </div>
            </div>

            {/* Real-time Rendering */}
            <div className="card p-8 bg-gradient-to-br from-coral-50 to-white border-l-4 border-coral-500 shadow-lg hover:shadow-xl transition-all duration-300">
              <div className="w-16 h-16 bg-gradient-to-br from-coral-400 to-coral-600 rounded-2xl flex items-center justify-center mb-6 shadow-lg">
                <svg
                  className="w-8 h-8 text-white"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M13 10V3L4 14h7v7l9-11h-7z"
                  />
                </svg>
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-4">
                Real-time Rendering
              </h3>
              <p className="text-gray-600 leading-relaxed mb-6">
                High-performance rendering engine that dynamically generates and
                updates environments in real-time, providing instant feedback
                and seamless interaction experiences.
              </p>
              <div className="space-y-3">
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-coral-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">60fps rendering</span>
                </div>
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-coral-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Instant updates</span>
                </div>
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-coral-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Smooth animations</span>
                </div>
              </div>
            </div>

            {/* State Management */}
            <div className="card p-8 bg-gradient-to-br from-gold-50 to-white border-l-4 border-gold-500 shadow-lg hover:shadow-xl transition-all duration-300">
              <div className="w-16 h-16 bg-gradient-to-br from-gold-400 to-gold-600 rounded-2xl flex items-center justify-center mb-6 shadow-lg">
                <svg
                  className="w-8 h-8 text-white"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"
                  />
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
                  />
                </svg>
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-4">
                State Management
              </h3>
              <p className="text-gray-600 leading-relaxed mb-6">
                Sophisticated state management system that tracks and preserves
                agent interactions, ensuring accurate evaluation and
                comprehensive behavioral analysis.
              </p>
              <div className="space-y-3">
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-gold-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Context preservation</span>
                </div>
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-gold-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">History tracking</span>
                </div>
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-gold-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Rollback capabilities</span>
                </div>
              </div>
            </div>

            {/* Event Simulation */}
            <div className="card p-8 bg-gradient-to-br from-gray-50 to-white border-l-4 border-gray-500 shadow-lg hover:shadow-xl transition-all duration-300">
              <div className="w-16 h-16 bg-gradient-to-br from-gray-400 to-gray-600 rounded-2xl flex items-center justify-center mb-6 shadow-lg">
                <svg
                  className="w-8 h-8 text-white"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M15 15l-2 5L9 9l11 4-5 2z"
                  />
                </svg>
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-4">
                Event Simulation
              </h3>
              <p className="text-gray-600 leading-relaxed mb-6">
                Comprehensive event simulation framework that accurately
                reproduces user interactions, providing realistic testing
                scenarios for agent evaluation.
              </p>
              <div className="space-y-3">
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-gray-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Click & touch events</span>
                </div>
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-gray-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Keyboard input</span>
                </div>
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-gray-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Gesture recognition</span>
                </div>
              </div>
            </div>

            {/* Cross-platform Support */}
            <div className="card p-8 bg-gradient-to-br from-warm-50 to-white border-l-4 border-warm-500 shadow-lg hover:shadow-xl transition-all duration-300">
              <div className="w-16 h-16 bg-gradient-to-br from-warm-400 to-warm-600 rounded-2xl flex items-center justify-center mb-6 shadow-lg">
                <svg
                  className="w-8 h-8 text-white"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9"
                  />
                </svg>
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-4">
                Cross-platform Support
              </h3>
              <p className="text-gray-600 leading-relaxed mb-6">
                Universal platform compatibility ensures consistent testing
                experiences across web, desktop, and mobile environments with
                platform-specific optimizations.
              </p>
              <div className="space-y-3">
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-warm-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Web browsers</span>
                </div>
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-warm-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Desktop applications</span>
                </div>
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-warm-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Mobile devices</span>
                </div>
              </div>
            </div>

            {/* Analytics & Insights */}
            <div className="card p-8 bg-gradient-to-br from-coral-50 to-white border-l-4 border-coral-500 shadow-lg hover:shadow-xl transition-all duration-300">
              <div className="w-16 h-16 bg-gradient-to-br from-coral-400 to-coral-600 rounded-2xl flex items-center justify-center mb-6 shadow-lg">
                <svg
                  className="w-8 h-8 text-white"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth="2"
                    d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"
                  />
                </svg>
              </div>
              <h3 className="text-xl font-bold text-gray-900 mb-4">
                Analytics & Insights
              </h3>
              <p className="text-gray-600 leading-relaxed mb-6">
                Advanced analytics engine provides detailed insights into agent
                performance, behavior patterns, and areas for improvement
                through comprehensive data analysis.
              </p>
              <div className="space-y-3">
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-coral-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Performance metrics</span>
                </div>
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-coral-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Behavior analysis</span>
                </div>
                <div className="flex items-center text-sm">
                  <svg
                    className="w-4 h-4 text-coral-500 mr-2"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                  >
                    <path
                      fillRule="evenodd"
                      d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                      clipRule="evenodd"
                    />
                  </svg>
                  <span className="text-gray-700">Real-time reporting</span>
                </div>
              </div>
            </div>
          </div>

          {/* CTA Section */}
          <div className="mt-16 text-center">
            <div className="bg-gradient-to-r from-warm-500 to-coral-500 rounded-3xl p-8 md:p-12 text-white relative overflow-hidden">
              <div className="absolute inset-0 opacity-10">
                <div className="absolute top-10 right-10 w-32 h-32 bg-white rounded-full"></div>
                <div className="absolute bottom-10 left-10 w-24 h-24 bg-white rounded-full"></div>
              </div>
              <div className="relative z-10">
                <h3 className="text-2xl md:text-3xl font-bold mb-4">
                  Ready to Test Your Agent?
                </h3>
                <p className="text-lg mb-8 opacity-90 max-w-2xl mx-auto">
                  Join the ScaleCUA benchmark platform and experience the most
                  comprehensive and fair evaluation system for GUI agents.
                </p>
                <CTAButtons
                  buttons={[
                    {
                      text: 'Get Started Today',
                      onClick: () => {},
                      variant: 'primary-on-warm',
                    },
                    {
                      text: 'View Documentation',
                      onClick: () => {},
                      variant: 'secondary-on-warm',
                    },
                  ]}
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Environment;
